### PR TITLE
msvc compatibility

### PR DESCRIPTION
**Pull request by justnope**
I've made some changes to allow it to compile in visual studio. I'm currently using it for lmms so not everything has been ported. I've split up the issues in several commits so it's easier to pick and choose if necessary.

### CODE REVIEW

**Comment by tresf** [comment]
Downstream temporary fork branch created [`ladspa-msvc`](https://github.com/LMMS/veal/tree/ladspa-msvc) while we wait for merge.  When merge is complete, downstream will need to:
* [ ] Sync from upstream (@JohannesLorenz)
* [ ] Bump the downstream submodule (@JohannesLorenz or @justnope)
* [ ] Delete the temporary fork branch (@JohannesLorenz)

Documenting here because downstream (LMMS) is adding MSVC support for all bundled plugins and upstream merging this PR is the trigger for downstream work.  I hope that's OK. 🍻

**Comment by boomshop** [comment]
Thanks!

**Comment by Rossmaxx** [comment]
Been searching on my own online to try compile lmms with ladspa on msvc and i just found this. Since it's been merged, how about restarting the efforts.

**Comment by tresf** [comment]
> Been searching on my own online to try compile lmms with ladspa on msvc and i just found this. Since it's been merged, how about restarting the efforts.

Probably better question for LMMS project?  LMMS operates on a fork called LMMS/veal, which still supports LADSPAv1.  Since LMMS is close to adding LV2 support, it may make more sense to spend time using upstream, but we'd need a volunteer to spearhead this effort.

**Pull request merged**
