### PR TITLE
Add filechanges to compile in Linux with gcc-6.2.0

### PR DESCRIPTION
**Pull request by HarryBroeken**
To get calf to compile on my box; I had to add some changes, mainly to make the compiler happy with the types.
I just wanted it compiled so I didn't go into any depth about the why of the changes; I can tell you evrything seems to work with these changes.
Thought you liked to know

### CODE REVIEW

**Comment by boomshop** [comment]
Since your pull request is rolling back some of the latest changes I'm curious if you're using the latest git to build from?

**Comment by HarryBroeken** [comment]
I just checked. As far as I can see my git-checkout is dated 12/26/2016.

**Comment by boomshop** [comment]
I wonder why you're removing all new `if (*params[param_post] > 0.5) { }` from modules_dist.cpp and re-add the cairo include in analyzer.cpp?

**Comment by HarryBroeken** [comment]
I will have a look in a couple of days. My first interest was in getting it compiled; it could be I've changed things I don't really remember doing.
At the moment there are some other things requiring my attention; I would love to immerse myself some more in the code, but there's no time at the moment. I hope I can get back to this in a couple of days.

**Comment by Jacalz** [comment]
This could probably be closed. Gcc6 is ancient technology by 2019...

**Comment by falkTX** [comment]
that is funny, and sad..
I still use gcc4 regularly here, nothing wrong with "just" C++11.

**Comment by JohannesLorenz** [comment]
We are heading towards 2024. Is still anyone here using a gcc 6 or less? :grin:

**Comment by JohannesLorenz** [comment]
I will close this due to inactivity and deprecation. Feel free to reopen if you really want to add this.

**Pull request closed without merging**
