### PR TITLE
Test if linker supports nodelete

### PR DESCRIPTION
**Pull request by david0**
The Mac OS linker does not support `-z,nodelete` so I added an check for that and omitted this flag to make calf compile on OS X.

### CODE REVIEW

**Comment by IvanDSM** [comment]
@boomshop, has the functionality of this pull request been included in the master?

**Comment by boomshop** [comment]
Not by now. I would like Krzysztof to review this request since he's responsible for make and autohell.

**Comment by JohannesLorenz** [comment]
@david0 Sorry for the slow reply. I was able to compile with MacOS now without this PR: https://github.com/calf-studio-gear/calf/actions/runs/6523823137 . Anyways, since you have a recent issue with this in david0/homebrew-audio#28, I guess it's best we just include your PR. I guess after 8 years, it should be stable enough? :grin:

**Comment by JohannesLorenz** [comment]
@david0 Friendly reminder that I would appreciate your input on this PR (see above post).

**Comment by david0** [comment]
@JohannesLorenz: Sorry for the delay, had to update my system to get XCode somewhat up to date 🙄 

This PR is still valid, since nodelete is not supported by OS X. Most likely you compiled without GTK, since only for this case  `-Wl,nodelete` is added.

**Comment by JohannesLorenz** [comment]
Hi @david0 . Your assumptions were correct. Now I added Gtk. However, even when I cherry-pick your commit onto my `github-actions` branch, I cannot compile: https://github.com/calf-studio-gear/calf/actions/runs/7515118130/job/20458734605 .

My github actions file does this:
```
      - name: Install dependencies
        run: brew install automake fluid-synth gtk+ cairo lv2
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
      - name: Build
        run: cmake --build build
```
Do you have any idea what I do wrong? How do you do it on your computer?

**Comment by JohannesLorenz** [comment]
@david0 Friendly reminder that I could need your help with compiling on macos-13 (please see above).

**Comment by JohannesLorenz** [comment]
Will merge, as this is indirectly confirmed in #345 .

Conflicts still need to be solved :smiley:

**Comment by JohannesLorenz** [comment]
PR for merge-conflicts-solving is up against david0's repo.

**Pull request merged**
