### PR TITLE
Fix memset with too small sizes

### PR DESCRIPTION
**Pull request by JohannesLorenz**

### CODE REVIEW

**Comment by falkTX** [comment]
Shouldn't this be something like:
```
        memset(ins, 0, sizeof(ins[0]) * in_count);
        memset(outs, 0, sizeof(outs[0]) * out_count);
        memset(params, 0, sizeof(params[0]) * params_count);
```

or does `sizeof(ins)` get deduced as `max(in_count, 1)` ?

**Comment by JohannesLorenz** [comment]
Sorry, my PR looks wrong indeed. `sizeof(ins)` already returns the size of the array in bytes, which is correct for using `memset`.

I had a compiler warning about this line of code, which confused me:

```
In file included from /data/cprogs/lmms/osc-plugin/plugins/LadspaEffect/calf/veal/src/monosynth.cpp:21:
/data/cprogs/lmms/osc-plugin/plugins/LadspaEffect/calf/veal/src/calf/giface.h: In instantiation of 'veal_plugins::audio_module<Metadata>::audio_module() [with Metadata = veal_plugins::monosynth_metadata]':
/data/cprogs/lmms/osc-plugin/plugins/LadspaEffect/calf/veal/src/monosynth.cpp:34:22:   required from here
/data/cprogs/lmms/osc-plugin/plugins/LadspaEffect/calf/veal/src/calf/giface.h:535:15: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
  535 |         memset(ins, 0, sizeof(ins));
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

but the following test program
```
#include <iostream>

constexpr const int in_count = IN_COUNT;

struct s_t {
        float ins[(in_count != 0) ? in_count : 1];
};

int main()
{
        struct s_t s;
        std::cout
                << sizeof(s.ins) << " "
                << sizeof(s.ins[0]) << " "
                << (sizeof(s.ins) * sizeof(s.ins[0])) << " " << std::endl;
}
```
shows you don't need to multiply with `sizeof(ins[0])` anymore:
```
$ clang++ -Wall -Wextra -Weverything -Wno-c++98-compat -Werror -DIN_COUNT=4 test.cpp -o test
$ ./test 
32 8 256
```

Looks like the compiler has an error?

**Comment by falkTX** [comment]
Your example code does not trigger the warning, does it? So it will work fine there.
Unless you can also make it trigger the compiler warning, it won't be a 1:1 test case.

The use of `memset(ins, 0, sizeof(ins));` does not seem right to me tbh, I would just replace it with:
```
memset(ins, 0, sizeof(float) * max(in_count, 1));
```
which is not really that much unreadable at all, I think...

**Comment by JohannesLorenz** [comment]
Not sure why it does not trigger that warning, but there have been [bug reports](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90728) of false positives in similar cases.

`memset(ins, 0, sizeof(ins));` should be correct, cppreference says "the result is the size of the static type of the expression". Your suggestion also works, but if you're going to change the size of the array, you may forget to change the size for the `memset`. I'd just close the PR, let's not change anything.

**Pull request closed without merging**
